<robot name="polar" xmlns:xacro="http://www.ros.org/wiki/xacro">
     <xacro:include filename="common_properties.xacro" />
    
    <xacro:property name="base_hight" value="0.02" />
    <xacro:property name="base_radius" value="0.1" />

    <xacro:property name="first_link_radius" value="0.02" />
    <xacro:property name="first_link_length" value="0.3" />

    <xacro:property name="second_link_radius" value="0.02" />
    <xacro:property name="second_link_length" value="0.3" />

    <xacro:property name="third_link_radius" value="0.01" />
    <xacro:property name="third_link_length" value="0.3" />

    <link name="base_footprint">
    </link>


    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_hight}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_hight}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <!-- add inertia -->
    </link>

    <link name="first_link">
        <visual>
            <geometry>
                <cylinder radius="${first_link_radius}" length="${first_link_length}" />
            </geometry>
            <origin xyz="0 0 ${first_link_length/2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${first_link_radius}" length="${first_link_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <!-- add inertia -->
    </link>
    
    <link name="second_link">
        <visual>
            <geometry>
                <cylinder radius="${second_link_radius}" length="${second_link_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${second_link_radius}" length="${second_link_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <!-- add inertia -->
    </link>
    
    <link name="third_link">
        <visual>
            <geometry>
                <cylinder radius="${third_link_radius}" length="${third_link_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${third_link_radius}" length="${third_link_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <!-- add inertia -->
    </link>
    

    <joint name="base_first_joint" type="revolute">
        <parent link="base_link" />
        <child link="first_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="-1.57" upper="1.57" velocity="100" effort="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>    

    <joint name="first_second_joint" type="revolute">
        <parent link="first_link" />
        <child link="second_link" />
        <origin xyz="0 0 ${first_link_length}" rpy="${pi/2.0} 0 0" />
        <axis xyz="1 0 0" />
        <limit lower="-1.57" upper="1.57" velocity="100" effort="100" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

    <joint name="second_third_joint" type="prismatic">
        <parent link="second_link" />
        <child link="third_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="0.0" upper="0.2" velocity="100" effort="100" />
    </joint>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    
</robot>